version: "3.5"
services:
  beacon-chain:
    image: "beacon-chain.lodestar-gnosis.dnp.dappnode.eth:0.1.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v1.10.0
    volumes:
      - "beacon-data:/var/lib/data"
    ports:
      - "19012:19012/tcp"
      - "19012:19012/udp"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    environment:
      DEBUG_LEVEL: info
      BEACON_API_PORT: 3500
      CHECKPOINT_SYNC_URL: ""
      P2P_PORT: 19012
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
  validator:
    image: "validator.lodestar-gnosis.dnp.dappnode.eth:0.1.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v1.10.0
    volumes:
      - "validator-data:/var/lib/data"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    environment:
      DEBUG_LEVEL: info
      HTTP_WEB3SIGNER: "http://web3signer.web3signer-gnosis.dappnode:9000"
      BEACON_NODE_ADDR: "http://beacon-chain.lodestar-gnosis.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-data: {}
  validator-data: {}
